### ISSUE TITLE
Comment entity

### ISSUE THREAD

**Issue by naz3eh** [Developer-DAO/Lens-Graph-Subgraph#10]

**Comment by naz3eh** [comment]
Hey @Amtaf, can you comment on this issue, som that I can assign you

**Comment by Amtaf** [comment]
Hey @Nazeeh21 i want to start working on the comment entity

**Comment by naz3eh** [comment]
Hey @Amtaf, all yours.
I would like to mention one small thing that pls fork from `feat/index-profile` banch, because the `main` branch has a `union` type in the schema and is currently not supported by the graph, thus will throw you an error while running the graph command

**Comment by naz3eh** [comment]
Is there any update on this? LMK if you're stuck somewhere or need my help

**Comment by Amtaf** [comment]
Oh btw im done lemme just cross check and do a PR ,then you can check from there so we can rectify any mistake

**Comment by naz3eh** [comment]
Sure, that sounds good. just mention me whenever you create it

**Comment by naz3eh** [comment]
Closed via #22
