### ISSUE TITLE
MirrorCreated

### ISSUE THREAD

**Issue by naz3eh** [Developer-DAO/Lens-Graph-Subgraph#16]

**Comment by rai-rakesh** [comment]
Hi @Nazeeh21 . I can work on this.

**Comment by naz3eh** [comment]
All yours @rai-rakesh

**Comment by naz3eh** [comment]
Is there any update on this? LMK if you're stuck somewhere or need my help

**Comment by andyrobert3** [comment]
solving this issue in this PR https://github.com/Developer-DAO/Lens-Graph-Subgraph/pull/30
@Nazeeh21

**Comment by naz3eh** [comment]
Closed by #30
