### ISSUE TITLE
Add contribution docs

### ISSUE THREAD

**Issue by naz3eh** [Developer-DAO/Lens-Graph-Subgraph#22]
Right now, it is difficult for any person to get to know where they can start contributing to the subgraph. So it would be good to have contribution docs that can guide about the files (mainly 3 important files which includes `subgraph.yaml`, `schema.graphql` and `lenshub.ts`) Also, which tools they can use to know about the data structures and events that are emitted.

**Comment by deepak-likes-code** [comment]
I think we can add this as part of the readme file? What do you think @Nazeeh21  ?

**Comment by naz3eh** [comment]
yeah, that could be done but I think would be better if we'll have a separate `contributions.md` file and put a reference to it in the readme. WDYT?

**Comment by deepak-likes-code** [comment]
Sure, that would work great. Assign it to me, I can pick this up

**Comment by naz3eh** [comment]
All yours! just one thing I'd like to mention that include the below thing in the contribution docs
https://github.com/Developer-DAO/Lens-Graph-Subgraph/issues/10#issuecomment-1240549201

**Comment by naz3eh** [comment]
Is there any update on this? LMK if you're stuck somewhere or need my help

**Comment by naz3eh** [comment]
closed via #25
