### ISSUE TITLE
Entities to add

### ISSUE THREAD

**Issue by naz3eh** [Developer-DAO/Lens-Graph-Subgraph#8]
These are the list of entities that are remained to add.

I've added a few entities which were required to deploy an MVP and query data. Lists of those entities are below:
- [x] Publication
- [x] Post
- [x] Mirror
- [x] FollowModule
- [x] ReactionTypes
- [x] CollectModules
- [x] Wallet
- [x] PublicationStats
- [x] ReactionTypes
- [x] Media
- [x] Erc20
- [x] ProfileMedia
- [x] ProfileStats
- [x] Transfer
------------------------------------
Below are the list for the entities that are remained to be defined
- [x] #10
- [x] #11
- [x] #12
- [x] #13

Any suggestions regarding the addition/deletion of any entities are welcome.

**Comment by naz3eh** [comment]
Here are some steps for writing the schema:
Consider for example that you want to write a schema for the `Comment` entity. Then just go to https://graphiql-online.com/ and enter this lens url https://api.lens.dev/. After that click on the voyager as shown in the video. This will show you all the relationships among different entities. Now to get a particular entity you are looking for (`Comment` in our case), click on the select dropdown from the bottom left and select that entity as shown in the video below. This will bring you down to that particular entity and now you are good to go to define the schema for that entity in `schema.graphql` file.

https://user-images.githubusercontent.com/56908732/188067814-94cac5f9-5b9b-46f6-b06d-c028f55c6a1a.mov

Hmu if you have any query related to this

**Comment by Amtaf** [comment]
I would like to work on defining the remaining entities

**Comment by naz3eh** [comment]
Hey @Amtaf, tysm for the heads up. This is the list of the issues to be solved, so can you please comment on the individual issues like #10, #11, #12, and #13, so that I can assign you all 4 of them? Or should I just straightway assign you all these issues? I'll go with what so ever suits you the best.

**Comment by Amtaf** [comment]
Hey @Nazeeh21 ill start with #10 when I'm done I can take the rest

**Comment by naz3eh** [comment]
Sure, that sounds great! Assigning that issue to you.

**Comment by Nazeeh21** [comment]
Sure, that sounds great! Assigning that issue to you.

**Comment by naz3eh** [comment]
Also, would like to mention one more thing that as currently `union` is not supported by graph in `schema`, create a branch from [index-profile](https://github.com/Developer-DAO/Lens-Graph-Subgraph/tree/feat/index-profile) branch. Otherwise will get an error similar to this `"Field 'collectModule': Unknown type 'CollectModule'"`. So please fork from [index-profile](https://github.com/Developer-DAO/Lens-Graph-Subgraph/tree/feat/index-profile) branch and work on top of that branch only. Thanks!

cc @Amtaf

**Comment by Amtaf** [comment]
Great I'll look into it @Nazeeh21 thanks

**Comment by therealharpaljadeja** [comment]
assign me #12

**Comment by naz3eh** [comment]
@therealharpaljadeja can you pls comment on that issue as well, so that I can assign you?

**Comment by andyrobert3** [comment]
Taking this issue, realised our Entities needs some refactoring

**Comment by andyrobert3** [comment]
@Nazeeh21 it looks like the issues linking to the Entities to be defined are all resolved

if there is nothing left, should we close this issue

**Comment by naz3eh** [comment]
Thanks for reminding @andyrobert3. I think we should close this now.
